# Generated by Django 2.1.3 on 2018-11-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_sentiment_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='adjust',
            new_name='adjustment',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ending',
            new_name='closing',
        ),
    ]
