# Generated by Django 2.1.3 on 2018-12-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0003_auto_20181124_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
